### ISSUE TITLE
is there any example or usage method?

### ISSUE THREAD

**Issue by bau720123** [passslot/cordova-plugin-passbook#1]
is there any example or usage method?

**Comment by GQuantrill** [comment]
Are there 2 example URI's we can use per chance?
I'm trying to prove a case whereby we are attempting to add two different passes at the same time

**Comment by passslot** [comment]
Adding multiple passes is not supported by this plugin, but you could extend it to be able to add multiple passes at once.

Since iOS 7 you can create a PKAddPassesViewController with multiple passes (see [Documentation initWithPasses:](https://developer.apple.com/library/prerelease/ios/documentation/PassKit/Reference/PKAddPassesViewController_Ref/index.html#//apple_ref/occ/instm/PKAddPassesViewController/initWithPasses:) )

You would have to update the CDVPassbook.m file at [those lines](https://github.com/passslot/cordova-plugin-passbook/blob/master/src/ios/CDVPassbook.m#L47,L76). In particular the download code will need to be a bit more complicated because it needs to wait for all passes to be downloaded, but otherwise it should be straight forward
